!INTERFILE  :=
imaging modality := PT
patient orientation := head_in
patient rotation :=  supine

name of data file := scatter_template.hs
originating system := unknown
!GENERAL DATA :=
!GENERAL IMAGE DATA :=
!type of data := PET
imagedata byte order := LITTLEENDIAN
!PET STUDY (General) :=
!PET data type := Emission
applied corrections := {None}
!number format := float
!number of bytes per pixel := 4
number of dimensions := 4
matrix axis label [4] := segment
!matrix size [4] := 1
matrix axis label [3] := view
!matrix size [3] := 16
matrix axis label [2] := axial coordinate
!matrix size [2] := { 4}
matrix axis label [1] := tangential coordinate
!matrix size [1] := 24
minimum ring difference per segment := { 0}
maximum ring difference per segment := { 0}
Scanner parameters:= 
Scanner type := unknown
Number of rings                          := 4
Number of detectors per ring             := 32
Inner ring diameter (cm)                 := 102
Average depth of interaction (cm)        := 0.7
Distance between rings (cm)              := 2.7
Default bin size (cm)                    := 2.5032
View offset (degrees)                    := 0
Maximum number of non-arc-corrected bins := 63
Default number of arc-corrected bins     := 0
Number of blocks per bucket in transaxial direction         := 0
Number of blocks per bucket in axial direction              := 0
Number of crystals per block in axial direction             := 0
Number of crystals per block in transaxial direction        := 0
Number of detector layers                                   := 1
Number of crystals per singles unit in axial direction      := -1
Number of crystals per singles unit in transaxial direction := -1
energy_resolution :=.22
reference energy (in keV):=511
end scanner parameters:=
effective central bin size (cm) := 2.21541

number of energy windows:=1
energy window lower level[1]:=350
energy window upper level[1]:=650

number of time frames := 1
image duration (sec)[1] := 1 ; defaults to -1 (i.e. unknown)
!END OF INTERFILE :=
